[package]
name = "laplacianos-compositor"
version = "0.1.0"
edition = "2024"
license = "PolyForm-Noncommercial-1.0.0"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
laplacianos-gfx   = { path = "../gfx" }
laplacianos-scene = { path = "../scene" }
libm          = { version = "0.2", default-features = false }
